//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.24 at 09:11:42 AM IST 
//


package com.sparsh.medical.getpatientdetailsresponse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Patients" type="{urn:com.sparsh.medical.getpatientdetailsresponse}Patients" minOccurs="0"/>
 *         &lt;element name="ServiceErrors" type="{urn:com.sparsh.medical.getpatientdetailsresponse}ServiceErrors" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "patients",
    "serviceErrors"
})
@XmlRootElement(name = "GetPatientDetailsResponse")
public class GetPatientDetailsResponse {

    @XmlElement(name = "Patients")
    protected Patients patients;
    @XmlElement(name = "ServiceErrors")
    protected ServiceErrors serviceErrors;

    /**
     * Default no-arg constructor
     * 
     */
    public GetPatientDetailsResponse() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public GetPatientDetailsResponse(final Patients patients, final ServiceErrors serviceErrors) {
        this.patients = patients;
        this.serviceErrors = serviceErrors;
    }

    /**
     * Gets the value of the patients property.
     * 
     * @return
     *     possible object is
     *     {@link Patients }
     *     
     */
    public Patients getPatients() {
        return patients;
    }

    /**
     * Sets the value of the patients property.
     * 
     * @param value
     *     allowed object is
     *     {@link Patients }
     *     
     */
    public void setPatients(Patients value) {
        this.patients = value;
    }

    /**
     * Gets the value of the serviceErrors property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceErrors }
     *     
     */
    public ServiceErrors getServiceErrors() {
        return serviceErrors;
    }

    /**
     * Sets the value of the serviceErrors property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceErrors }
     *     
     */
    public void setServiceErrors(ServiceErrors value) {
        this.serviceErrors = value;
    }

}
