//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.24 at 09:11:42 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:com.sparsh.medical.getpatientdetailsresponse", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.sparsh.medical.getpatientdetailsresponse;
