//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.24 at 09:11:42 AM IST 
//


package com.sparsh.medical.getpatientdetailsresponse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PatientHistoryDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PatientHistoryDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Decease" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StillOnMedication" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PatientHistoryDetail", propOrder = {
    "decease",
    "stillOnMedication",
    "description"
})
public class PatientHistoryDetail {

    @XmlElement(name = "Decease", required = true)
    protected String decease;
    @XmlElement(name = "StillOnMedication")
    protected boolean stillOnMedication;
    @XmlElement(name = "Description", required = true)
    protected String description;

    /**
     * Default no-arg constructor
     * 
     */
    public PatientHistoryDetail() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public PatientHistoryDetail(final String decease, final boolean stillOnMedication, final String description) {
        this.decease = decease;
        this.stillOnMedication = stillOnMedication;
        this.description = description;
    }

    /**
     * Gets the value of the decease property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecease() {
        return decease;
    }

    /**
     * Sets the value of the decease property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecease(String value) {
        this.decease = value;
    }

    /**
     * Gets the value of the stillOnMedication property.
     * 
     */
    public boolean isStillOnMedication() {
        return stillOnMedication;
    }

    /**
     * Sets the value of the stillOnMedication property.
     * 
     */
    public void setStillOnMedication(boolean value) {
        this.stillOnMedication = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
